# @host = http://localhost:3000/api 
@host= https://api-store-7fl7.onrender.com

GET {{host}}/products

### 

POST {{host}}/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjc0ZDgyMTFlZmIwYmE2YjI1ZTJjN2FlIiwiaWF0IjoxNzMzMTQwNTY1fQ.AA2hjrEMqlnf5TONyMAO8CbKAFYvW5fjfC6WAjl-dRs

{
    "name" : "Tiki Masala",
    "description": "Dont du del mi whad do do!",
    "price": 34,
    "department": "hogar",
    "stock": 180,
    "avaliable": true
}


### 

GET {{host}}/products/671f6f8b2bede92b1af1a39c

### 

GET {{host}}/products/price/250/450

###

GET {{host}}/products/actives


#########
# USERS #
#########

POST {{host}}/users/register
Content-Type: application/json

{
    "username": "Carlos",
    "email": "awaitAlwais@gmail.com",
    "password": "12345",
    "role": "regular"
}

###

POST {{host}}/users/login
Content-Type: application/json

{
    "email": "awaitAlwais@gmail.com",
    "password": "12345"
}